#!/usr/bin/env python3
# Author: Roberto Navoni, member of the ArduPilot Dev Team
# Contact: r.navoni74@gmail.com
# Developed by Roberto Navoni — DelphyAI LAB
# For information: r.navoni74@gmail.com
"""Regenerate robot profiles, PPO configs and robot pages from tools/robots/catalog.py.

    python tools/robots/build_catalog.py            # profiles + ppo.yaml + docs
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from catalog import LINK_TEXT, MLP_HIDDEN, ROBOTS, STATUS_TEXT  # noqa: E402
from common import REPO_ROOT, robot_dir  # noqa: E402

PPO_DEFAULTS = {
    "num_envs": 2048, "num_steps_per_env": 24, "max_iterations": 2000,
    "learning_rate": 1.0e-3, "schedule": "adaptive", "desired_kl": 0.01,
    "gamma": 0.99, "lam": 0.95, "clip_param": 0.2, "entropy_coef": 0.01,
    "value_loss_coef": 1.0, "num_learning_epochs": 5, "num_mini_batches": 4, "max_grad_norm": 1.0,
}


def obs_dim(r: dict) -> int:
    return 3 + 3 + 3 * len(r["joint_names"]) + 3 + r.get("extra_cmd_dim", 0)


def profile_for(rid: str, r: dict) -> dict:
    n = len(r["joint_names"])
    assert len(r["q0"]) == n, f"{rid}: q0 has {len(r['q0'])} values for {n} joints"
    return {
        "robot_id": rid,
        "nnm_robot": r["index"],
        "class": r["class"],
        "display_name": r["display_name"],
        "n_joints": n,
        "obs_dim": obs_dim(r),
        "rate_hz": r["rate_hz"],
        "q0": [round(float(v), 6) for v in r["q0"]],
        "joint_names": r["joint_names"],
        "servo_fn0": 94,
        "servos": r["servos"],
        "link": r["link"],
        "status": r["status"],
        "upstream": r["upstream"],
        "sim": r["sim"],
    }


def ppo_for(rid: str, r: dict) -> dict:
    return {
        "robot_id": rid,
        "network": {
            "actor_hidden": list(MLP_HIDDEN), "critic_hidden": list(MLP_HIDDEN), "activation": "elu",
            "init_noise_std": 1.0, "obs_normalization": True,
        },
        "quantization": {"weights": "int8_per_row", "qat": True, "activations": "float32"},
        "ppo": dict(PPO_DEFAULTS),
        "env": {
            "policy_hz": r["rate_hz"], "loop_hz": 200, "gravity_source": "ap_imu_filter",
            "att_tau": 0.5, "act_max": 2.0, "pwm_quantization": True,
            "command_ranges": r["command_ranges"],
            "p_zero_command": 0.2, "p_no_lateral": 0.3, "episode_s": 20.0, "fall_tilt_deg": 60.0,
            "gyro_noise": 0.02, "accel_noise": 0.05, "obs_delay_steps_max": 1,
            "reward": {"track_lin_vel": 2.0, "track_ang_vel": 2.0, "upright": 2.0, "pose": 1.0,
                       "action_rate": -0.8},
        },
    }


PPO_HEADER = """# PPO architecture and ArduPilot-compatible training environment for {name}.
# Generated by tools/robots/build_catalog.py from tools/robots/catalog.py.
# Network: {obs} -> 512 -> 256 -> 128 -> {n}, ELU: the MicroDuck network validated on a Pixhawk 6C.
# Read by tools/robots/train_velocity.py and tools/robots/nnm_env.py.
"""


def write_robot_files() -> None:
    for rid, r in ROBOTS.items():
        d = robot_dir(rid) / "robot"
        d.mkdir(parents=True, exist_ok=True)
        (d / "profile.json").write_text(json.dumps(profile_for(rid, r), indent=2, ensure_ascii=False) + "\n")
        hdr = PPO_HEADER.format(name=r["display_name"], obs=obs_dim(r), n=len(r["joint_names"]))
        (d / "ppo.yaml").write_text(hdr + yaml.safe_dump(ppo_for(rid, r), sort_keys=False, width=110))
        (robot_dir(rid) / "policies").mkdir(exist_ok=True)
    print(f"wrote profile.json + ppo.yaml for {len(ROBOTS)} robots")


if __name__ == "__main__":
    write_robot_files()
    if "--docs" in sys.argv or len(sys.argv) == 1:
        from build_catalog_docs import write_docs  # noqa: E402
        write_docs(ROBOTS, STATUS_TEXT, LINK_TEXT, REPO_ROOT)
