#!/usr/bin/env python3
"""Export the MicroDuck Cartan policy (CartanNetwork + DiLU, arXiv:2505.24353) from its ONNX to a C header.

Graph (mjlab_microduck.models.cartan_network, export-safe variant):
  x_n = (obs - mean) / std
  p   = W_in x_n + b_in                       (paint dim q)
  h   = [0 ; p]                               (cartan c = h[0], fiber f = h[1:])
  for each layer l (n_hidden):
      paint = W_l f + b_l
      c, f  = c, paint
      beta:  c += beta0 ; f += exp(-c_old) * beta_rest      (solvable_mul(beta, h))
      theta: fiber rotation with unit theta (see cartan_forward in microduck_infer.c)
      if l < last: f = DiLU(f) = (ELU(f) + 0.1 f) / 1.1
  out = W_head (f * exp(c)) + b_head

Weights are read from the ONNX initializers; theta is normalized here (F.normalize eps 1e-6).

    python tools/export_cartan_c.py policies/microduck_cartan_ac_2048x2000_it1999.onnx \
        --out ardupilot/libraries/AP_MicroDuck/policy_cartan.h --name cartan
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import onnx
from onnx import numpy_helper


def fmt_array(a: np.ndarray, per_line: int = 8) -> str:
    flat = a.astype(np.float32).ravel()
    return "\n".join("    " + ", ".join(f"{v:.8e}f" for v in flat[i : i + per_line]) + ","
                     for i in range(0, flat.size, per_line))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("onnx_path")
    ap.add_argument("--out", required=True)
    ap.add_argument("--name", default="cartan")
    args = ap.parse_args()

    m = onnx.load(args.onnx_path)
    g = m.graph
    inits = {t.name: numpy_helper.to_array(t) for t in g.initializer}
    meta = {p.key: p.value for p in m.metadata_props}
    nodes = list(g.node)
    # normalizer: the Sub/Div pair fed by the graph input (Constant nodes may precede them)
    sub = next(n for n in nodes if n.op_type == "Sub" and g.input[0].name in n.input)
    div = next(n for n in nodes if n.op_type == "Div" and sub.output[0] in n.input)
    mean = inits[sub.input[1]].reshape(-1)
    std = inits[div.input[1]].reshape(-1)

    W_in = inits["backbone.in_proj.weight"]          # (q, obs)
    b_in = inits["backbone.in_proj.bias"]
    W_head = inits["backbone.head.weight"]           # (act, q)
    b_head = inits["backbone.head.bias"]
    q = W_in.shape[0]
    obs_dim = W_in.shape[1]
    act_dim = W_head.shape[0]

    # layer weights: MatMul B operands (in, out) in graph order; betas: Expand initializers (1, q+1)
    matmul_B = [inits[n.input[1]] for n in nodes if n.op_type == "MatMul" and n.input[1] in inits and inits[n.input[1]].shape == (q, q)]
    betas = [inits[n.input[0]] for n in nodes if n.op_type == "Expand" and n.input[0] in inits and inits[n.input[0]].shape == (1, q + 1)]
    n_layers = len(matmul_B)
    assert n_layers == len(betas), (n_layers, len(betas))
    layers = []
    for l in range(n_layers):
        W = matmul_B[l].T.copy()                     # (out, in) row-major: paint[o] = sum_i W[o][i] f[i]
        b = inits[f"backbone.layers.{l}.bias_paint"]
        beta = betas[l].reshape(-1)
        th = inits[f"backbone.layers.{l}.theta_raw"].reshape(-1)
        th = th / max(np.linalg.norm(th), 1e-6)
        layers.append((W, b, beta, th))

    default_pose = [float(x) for x in meta.get("default_joint_pos", "").split(",") if x]
    N = args.name.upper()
    out = [
        "// Auto-generated by tools/export_cartan_c.py — do not edit.",
        f"// Source: {Path(args.onnx_path).name}  run={meta.get('run_path', '?')}",
        f"// Cartan network: obs {obs_dim} -> paint {q} -> {n_layers} CartanLinear(+DiLU) -> act {act_dim}",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define {N}_OBS_DIM {obs_dim}",
        f"#define {N}_ACT_DIM {act_dim}",
        f"#define {N}_PAINT {q}",
        f"#define {N}_N_LAYERS {n_layers}",
        "",
        f"static const float {args.name}_obs_mean[{obs_dim}] = {{\n{fmt_array(mean)}\n}};",
        f"static const float {args.name}_obs_std[{obs_dim}] = {{\n{fmt_array(std)}\n}};",
        f"static const float {args.name}_in_W[{q * obs_dim}] = {{\n{fmt_array(W_in)}\n}};",
        f"static const float {args.name}_in_b[{q}] = {{\n{fmt_array(b_in)}\n}};",
    ]
    for l, (W, b, beta, th) in enumerate(layers):
        out.append(f"static const float {args.name}_W{l}[{q * q}] = {{\n{fmt_array(W)}\n}};")
        out.append(f"static const float {args.name}_b{l}[{q}] = {{\n{fmt_array(b)}\n}};")
        out.append(f"static const float {args.name}_beta{l}[{q + 1}] = {{\n{fmt_array(beta)}\n}};")
        out.append(f"static const float {args.name}_theta{l}[{q + 1}] = {{\n{fmt_array(th)}\n}};")
    out.append(f"static const float {args.name}_head_W[{act_dim * q}] = {{\n{fmt_array(W_head)}\n}};")
    out.append(f"static const float {args.name}_head_b[{act_dim}] = {{\n{fmt_array(b_head)}\n}};")
    out.append(f"static const float *const {args.name}_W[{n_layers}] = {{ {', '.join(f'{args.name}_W{l}' for l in range(n_layers))} }};")
    out.append(f"static const float *const {args.name}_b[{n_layers}] = {{ {', '.join(f'{args.name}_b{l}' for l in range(n_layers))} }};")
    out.append(f"static const float *const {args.name}_beta[{n_layers}] = {{ {', '.join(f'{args.name}_beta{l}' for l in range(n_layers))} }};")
    out.append(f"static const float *const {args.name}_theta[{n_layers}] = {{ {', '.join(f'{args.name}_theta{l}' for l in range(n_layers))} }};")
    if default_pose:
        out.append(f"static const float {args.name}_default_pose[{len(default_pose)}] = {{ {', '.join(f'{v:.4f}f' for v in default_pose)} }};")
    total = 2 * obs_dim + W_in.size + b_in.size + sum(W.size + b.size + beta.size + th.size for W, b, beta, th in layers) + W_head.size + b_head.size
    out.append(f"// total floats: {total} ({total * 4 / 1024:.0f} KB float32)")
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(out) + "\n")
    print(f"wrote {args.out}: obs {obs_dim} -> paint {q} x {n_layers} -> act {act_dim}, {total} floats ({total * 4 / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
