#!/usr/bin/env python3
"""Export a NNMixer MLP policy (ONNX with baked EmpiricalNormalization) to a C header.

The exported graph is: Sub(mean) -> Div(std) -> [Gemm -> Elu] x3 -> Gemm.
We emit float32 arrays for mean/std and each Gemm (weight [out,in] row-major, bias [out]),
plus the metadata needed by the firmware (default joint pose, joint names).

Usage:
    python tools/export_policy_c.py policies/microduck_mlp_2048x2000_it1999.onnx \
        --out ardupilot/libraries/AP_NNMixer/policy_mlp.h --name mlp
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import onnx
from onnx import numpy_helper


def fmt_array(a: np.ndarray, per_line: int = 8) -> str:
    flat = a.astype(np.float32).ravel()
    lines = []
    for i in range(0, flat.size, per_line):
        chunk = flat[i : i + per_line]
        lines.append("    " + ", ".join(f"{v:.8e}f" for v in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("onnx_path")
    ap.add_argument("--out", required=True)
    ap.add_argument("--name", default="mlp", help="C symbol prefix (e.g. mlp)")
    args = ap.parse_args()

    m = onnx.load(args.onnx_path)
    g = m.graph
    inits = {t.name: numpy_helper.to_array(t) for t in g.initializer}
    meta = {p.key: p.value for p in m.metadata_props}

    nodes = list(g.node)
    assert nodes[0].op_type == "Sub" and nodes[1].op_type == "Div", "expected baked normalizer (Sub, Div) at graph start"
    mean = inits[nodes[0].input[1]].reshape(-1)
    std = inits[nodes[1].input[1]].reshape(-1)
    layers = []
    for n in nodes[2:]:
        if n.op_type == "Gemm":
            attrs = {a.name: onnx.helper.get_attribute_value(a) for a in n.attribute}
            W = inits[n.input[1]]
            b = inits[n.input[2]]
            if not attrs.get("transB", 0):
                W = W.T
            layers.append({"W": W, "b": b, "act": None})
        elif n.op_type == "Elu":
            alpha = {a.name: onnx.helper.get_attribute_value(a) for a in n.attribute}.get("alpha", 1.0)
            assert abs(alpha - 1.0) < 1e-6, "only ELU alpha=1 supported"
            layers[-1]["act"] = "elu"
        else:
            raise SystemExit(f"unsupported op in MLP export: {n.op_type}")

    obs_dim = mean.size
    act_dim = layers[-1]["W"].shape[0]
    assert layers[0]["W"].shape[1] == obs_dim
    default_pose = [float(x) for x in meta.get("default_joint_pos", "").split(",") if x]
    joint_names = meta.get("joint_names", "").split(",")

    N = args.name.upper()
    out = []
    out.append("// Author: Roberto Navoni, member of the ArduPilot Dev Team")
    out.append("// Contact: r.navoni74@gmail.com")
    out.append("// Developed by Roberto Navoni — DelphyAI LAB")
    out.append("// For information: r.navoni74@gmail.com")
    out.append("// Auto-generated by tools/export_policy_c.py — do not edit.")
    out.append(f"// Source: {Path(args.onnx_path).name}  run={meta.get('run_path', '?')}")
    out.append(f"// obs {obs_dim} -> act {act_dim}; layers: " + " -> ".join(f"{l['W'].shape[1]}x{l['W'].shape[0]}{'+ELU' if l['act'] else ''}" for l in layers))
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"#define {N}_OBS_DIM {obs_dim}")
    out.append(f"#define {N}_ACT_DIM {act_dim}")
    out.append(f"#define {N}_N_LAYERS {len(layers)}")
    dims = [layers[0]["W"].shape[1]] + [l["W"].shape[0] for l in layers]
    out.append(f"static const uint16_t {args.name}_dims[{len(dims)}] = {{ {', '.join(str(d) for d in dims)} }};")
    out.append(f"static const uint8_t {args.name}_act[{len(layers)}] = {{ {', '.join('1' if l['act'] else '0' for l in layers)} }}; // 1 = ELU")
    out.append("")
    out.append(f"static const float {args.name}_obs_mean[{obs_dim}] = {{\n{fmt_array(mean)}\n}};")
    out.append(f"static const float {args.name}_obs_std[{obs_dim}] = {{\n{fmt_array(std)}\n}};")
    for i, l in enumerate(layers):
        o, n_in = l["W"].shape
        out.append(f"// layer {i}: W[{o}][{n_in}] row-major, b[{o}]")
        out.append(f"static const float {args.name}_W{i}[{o * n_in}] = {{\n{fmt_array(l['W'])}\n}};")
        out.append(f"static const float {args.name}_b{i}[{o}] = {{\n{fmt_array(l['b'])}\n}};")
    out.append(f"static const float *const {args.name}_W[{len(layers)}] = {{ {', '.join(f'{args.name}_W{i}' for i in range(len(layers)))} }};")
    out.append(f"static const float *const {args.name}_b[{len(layers)}] = {{ {', '.join(f'{args.name}_b{i}' for i in range(len(layers)))} }};")
    if default_pose:
        out.append("")
        out.append(f"// default joint pose (rad), same order as joint_names: {','.join(joint_names)}")
        out.append(f"static const float {args.name}_default_pose[{len(default_pose)}] = {{ {', '.join(f'{v:.4f}f' for v in default_pose)} }};")
    total = sum(l["W"].size + l["b"].size for l in layers) + 2 * obs_dim
    out.append("")
    out.append(f"// total floats: {total} ({total * 4 / 1024:.0f} KB float32)")
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(out) + "\n")
    print(f"wrote {args.out}: obs {obs_dim} -> act {act_dim}, {len(layers)} layers, {total} floats ({total * 4 / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
